{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Airhumidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"some_data\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"testing/airhumidity\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"1767eedaab51\")"
    }
   ]
  },
  {
   "title": "Airtemperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"some_data\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"testing/airtemperature\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"1767eedaab51\")"
    }
   ]
  },
  {
   "title": "Soilmoisture",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"some_data\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"moisture\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"testing/soilmoisture\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"1767eedaab51\")"
    },
    {},
    {}
   ]
  }
 ]
}